"""
Template Generator - WPD/PRD Document Templates

Handles:
- WPD template generation with version management
- PRD template generation
- Automatic version management (N1.N2.N3)
- Template validation
- Rule enforcement for document structure

Template Types:
- WPD: Work Plan Documents (L0-L3 grades)
- PRD: Progress Results Documents

DESTRUCTIVE REFACTOR: VersionInfo moved to models.core.version
- VersionInfo now imported from canonical models
- This module now only contains template generation logic

TODO(refactor-dataclasses): Verify all consumers import VersionInfo from canonical models
PR: copilot/refactor-dataclasses-centralization
"""

from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Literal
import sys

# Import VersionInfo from canonical models
sys.path.insert(0, str(Path(__file__).parent.parent))
from models.core.version import VersionInfo


class TemplateGenerator:
    """
    Generates document templates for WPD and PRD
    
    Features:
    - Automatic version management
    - Template validation
    - Rule enforcement
    - Timestamp generation
    """
    
    def __init__(self, workspace_root: Path):
        self.workspace_root = workspace_root
    
    def generate_wpd_template(
        self,
        Part_N: str,
        title: str,
        wpd_grade: Literal["L0", "L1", "L2", "L3"] = "L1",
        version: str = "1.0.0",
        description: str = ""
    ) -> str:
        """
        Generate WPD template
        
        Args:
            Part_N: Step number (e.g., "5", "5.1", "5.1.2")
            title: Document title
            wpd_grade: WPD grade level
            version: Version string
            description: Optional description
            
        Returns:
            Template content as string
        """
        timestamp = datetime.now().strftime('%Y-%m-%d')
        
        template = f"""# P{Part_N}: {title}

**WPD_grade**: {wpd_grade}
**Version**: {version}
**Status**: 📋 PENDING
**Created**: {timestamp}

## 📋 Goal

{description if description else "Define the goal of this work plan."}

## ✅ Success Criteria

1. Define measurable success criteria
2. List completion requirements
3. Specify validation methods

## 🔧 Scope

### In Scope
- Define what is included in this work plan

### Out of Scope
- Define what is explicitly excluded

## 🔧 Execution Plan

### Phase {Part_N}.1: [Phase Name]

**Objective**: [Describe phase objective]

**Tasks**:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Expected Output**: [Describe expected output]

## 📝 Implementation Notes

Implementation details will be added as work progresses.

## 🔗 References

### Parent Documents
- [NextTask-2.md](../NextTask-2.md)

### Related Documents
- TBD

## 📅 Timeline

**Started**: {timestamp}
**Target Completion**: TBD

---
*Generated by TemplateGenerator*
"""
        return template
    
    def generate_prd_template(
        self,
        Part_N: str,
        title: str,
        wpd_source: Optional[str] = None,
        version: str = "1.0.0"
    ) -> str:
        """
        Generate PRD template
        
        Args:
            Part_N: Step number
            title: Document title
            wpd_source: Source WPD document path
            version: Version string
            
        Returns:
            Template content as string
        """
        timestamp = datetime.now().strftime('%Y-%m-%d')
        
        wpd_ref = f"- **Source WPD**: [{wpd_source}](../{wpd_source})" if wpd_source else "- **Source WPD**: TBD"
        
        template = f"""# PRD-P{Part_N}: {title} - Results

**Version**: {version}
**Status**: 📋 PENDING
**Generated**: {timestamp}

## 📋 Overview

This document tracks the implementation results for P{Part_N}: {title}.

{wpd_ref}

## 📊 Implementation Progress

**Overall Progress**: 0%

### Completed Tasks
- None

### In Progress
- TBD

### Pending
- All tasks from source WPD

## ✅ Validation Results

### Tests Passed
- None

### Tests Failed
- None

### Tests Pending
- All tests

## 📝 Implementation Notes

Notes will be added as implementation progresses.

## 🔍 Issues Found & Resolutions

### Open Issues
- None

### Resolved Issues
- None

## 🔗 References

### Source Documents
- [P{Part_N} WPD](../P{Part_N}/P{Part_N}-{title}.md)

### Related Documents
- TBD

---
*Generated by TemplateGenerator*
"""
        return template
    
    def create_wpd_file(
        self,
        Part_N: str,
        title: str,
        wpd_grade: Literal["L0", "L1", "L2", "L3"] = "L1",
        version: str = "1.0.0",
        description: str = ""
    ) -> Dict[str, any]:
        """
        Create WPD file from template
        
        Args:
            Part_N: Step number
            title: Document title
            wpd_grade: WPD grade
            version: Version string
            description: Description
            
        Returns:
            Result dict with file path
        """
        # Generate path
        wpd_dir = self.workspace_root / "docs_2" / f"P{Part_N.split('.')[0]}"
        wpd_dir.mkdir(parents=True, exist_ok=True)
        
        wpd_filename = f"P{Part_N}-{title}.md"
        wpd_path = wpd_dir / wpd_filename
        
        # Check if file exists
        if wpd_path.exists():
            return {
                "success": False,
                "error": f"File already exists: {wpd_path}"
            }
        
        # Generate template
        content = self.generate_wpd_template(Part_N, title, wpd_grade, version, description)
        
        # Write file
        wpd_path.write_text(content, encoding='utf-8')
        
        return {
            "success": True,
            "path": str(wpd_path),
            "wpd_grade": wpd_grade,
            "version": version
        }
    
    def create_prd_file(
        self,
        Part_N: str,
        title: str,
        wpd_source: Optional[str] = None,
        version: str = "1.0.0"
    ) -> Dict[str, any]:
        """
        Create PRD file from template
        
        Args:
            Part_N: Step number
            title: Document title
            wpd_source: Source WPD path
            version: Version string
            
        Returns:
            Result dict with file path
        """
        # Generate path
        prd_dir = self.workspace_root / "docs_2" / "prd"
        prd_dir.mkdir(parents=True, exist_ok=True)
        
        prd_filename = f"PRD-P{Part_N}.md"
        prd_path = prd_dir / prd_filename
        
        # Check if file exists
        if prd_path.exists():
            return {
                "success": False,
                "error": f"File already exists: {prd_path}"
            }
        
        # Generate template
        content = self.generate_prd_template(Part_N, title, wpd_source, version)
        
        # Write file
        prd_path.write_text(content, encoding='utf-8')
        
        return {
            "success": True,
            "path": str(prd_path),
            "version": version
        }
    
    @staticmethod
    def parse_version(version_str: str) -> VersionInfo:
        """
        Parse version string to VersionInfo.
        
        Delegates to VersionInfo.parse() from canonical models.
        """
        return VersionInfo.parse(version_str)


__all__ = ["TemplateGenerator", "VersionInfo"]
